src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $registerId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $activatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Scenario::class, mappedBy="user")
     */
    private $scenarios;

    /**
     * @ORM\OneToMany(targetEntity=Character::class, mappedBy="user")
     */
    private $characters;

    public function __construct()
    {
        $this->scenarios = new ArrayCollection();
        $this->characters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getRegisterId(): ?string
    {
        return $this->registerId;
    }

    public function setRegisterId(?string $registerId): self
    {
        $this->registerId = $registerId;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }


    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getActivatedAt(): ?\DateTimeInterface
    {
        return $this->activatedAt;
    }

    public function setActivatedAt(?\DateTimeInterface $activatedAt): self
    {
        $this->activatedAt = $activatedAt;

        return $this;
    }

    /**
     * @return Collection|Scenario[]
     */
    public function getScenarios(): Collection
    {
        return $this->scenarios;
    }

    public function addScenario(Scenario $scenario): self
    {
        if (!$this->scenarios->contains($scenario)) {
            $this->scenarios[] = $scenario;
            $scenario->setUser($this);
        }

        return $this;
    }

    public function removeScenario(Scenario $scenario): self
    {
        if ($this->scenarios->removeElement($scenario)) {
            // set the owning side to null (unless already changed)
            if ($scenario->getUser() === $this) {
                $scenario->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Character[]
     */
    public function getCharacters(): Collection
    {
        return $this->characters;
    }

    public function addCharacter(Character $character): self
    {
        if (!$this->characters->contains($character)) {
            $this->characters[] = $character;
            $character->setUser($this);
        }

        return $this;
    }

    public function removeCharacter(Character $character): self
    {
        if ($this->characters->removeElement($character)) {
            // set the owning side to null (unless already changed)
            if ($character->getUser() === $this) {
                $character->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\LoginType;
use App\Form\UserPasswordType;
use App\Form\UserProfileType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/connexion", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('home');
        }

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('user/login.html.twig',
            [
                'last_username' => $lastUsername,
                'error' => $error,
            ]
        );
    }

    /**
     * @Route("/deconnexion", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    /**
     * @Route("/ton-profil", name="user.profile")
     */
    public function profile(Request $request, EntityManagerInterface $manager, ValidatorInterface $validator): Response
    {
        $user = $this->getUser();

        $form = $this->createForm(UserProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $manager->persist($user);

            $manager->flush();

            $this->addFlash('success', 'ton profil a été sauvegardé');

            return $this->redirect($request->getUri());
        } else {
            $errors = $validator->validate($user);
            if (count($errors) > 0) {
                $this->addFlash('danger', 'user.profile.errors.unique');
            }
        }

        return $this->render('user/profile.html.twig',
            [
                'form' => $form->createView(),
            ]);
    }

    /**
     * @Route("/modifie-ton-mot-de-passe", name="user.password")
     */
    public function password(Request $request, EntityManagerInterface $manager, ValidatorInterface $validator, UserPasswordEncoderInterface $encoder): Response
    {
        $user = $this->getUser();

        $form = $this->createForm(UserPasswordType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword($encoder->encodePassword($user, $form->get('password')->getData()));
            $manager->persist($user);

            $manager->flush();

            $this->addFlash('success', 'ton mot de passe a été modifié');

            return $this->render('user/profile.html.twig',
                [
                    'form' => $form->createView(),
                ]);
        } else {
            $errors = $validator->validate($form);

            if (count($errors) > 0) {
                $this->addFlash('danger', $errors[0]->getMessage());
            }
        }

        return $this->render('user/password.html.twig',
            [
                'form' => $form->createView(),
            ]);
    }
}

templates/user/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'pages.login.title' | trans | capitalize }}{% endblock %}

{% block body_class %}login{% endblock %}

{% block body %}
    <article class="aside">
        <section>
            <h1>{{ 'pages.login.title' | trans | capitalize }}</h1>

            {% if error %}
                <div class="app_alert danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}

            {% if app.user %}
                <div class="app_alert warning">
                    You are logged in as {{ app.user.username }},
                    <a href="{{ path('app_logout') }}">Logout</a>
                </div>
            {% endif %}

            <form class="app_form" method="post">
                <div class="app_form_group">
                    <input type="email" value="{{ last_username }}" name="login_email" id="login_email" class="app_form_control" placeholder="{{ 'login.email.placeholder' | trans }}" autocomplete="email" required autofocus />
                    <label for="login_email">{{ 'login.email.label' | trans | capitalize }}</label>
                </div>

                <div class="app_form_group">
                    <input type="password" name="login_password" id="login_password" class="app_form_control" autocomplete="current-password" required />
                    <label for="login_password">{{ 'login.password.label' | trans | capitalize }}</label>
                </div>

                {#
                Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                See https://symfony.com/doc/current/security/remember_me.html
                <div class="app_form-group">
                    <div class="checkbox mb-3">
                        <label><input type="checkbox" name="_remember_me"> Remember me</label>
                    </div>
                </div>
                #}

                <div class="app_form_group mb_0">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" />
                    <button class="app_button cta" type="submit">{{ 'login.submit.label' | trans | capitalize }}</button>
                </div>
            </form>
        </section>

        <aside>
            <h2>{{ 'default.more' | trans | capitalize }}</h2>

            <a href="{{ path('contact') }}" class="app_button cta" title="{{ 'pages.contact.title' | trans | capitalize }}">
                {{ 'pages.login.aside.join' | trans | capitalize }}
            </a>

            <a href="{{ path('app_forgot_password_request') }}" class="app_button" title="{{ 'pages.forgot.title' | trans | capitalize }}">
                {{ 'pages.forgot.menu' | trans | capitalize }}
            </a>
        </aside>
    </article>
{% endblock %}

templates/user/password.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'pages.user.password.title' | trans | capitalize }}{% endblock %}

{% block body_class %}user{% endblock %}

{% block body %}
    <article class="aside">
        <section>
            <h1>{{ 'pages.user.password.title' | trans | capitalize }}</h1>

            <!-- Flash messages -->
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    {% if loop.first %}
                        <div class="app_alert {{ label }}">
                            {{ message | trans | capitalize }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}

            {{ form_start(form, { attr: { 'class': 'app_form'}}) }}
            <div class="app_grid two">
                <div class="app_form_group app_grid_item">
                    {{ form_widget(form.password.first) }}
                    <label for="{{ form.password.first.vars.id }}">{{ form.password.first.vars.label | trans | capitalize }}</label>
                </div>

                <div class="app_form_group app_grid_item">
                    {{ form_widget(form.password.second) }}
                    <label for="{{ form.password.second.vars.id }}">{{ form.password.second.vars.label | trans | capitalize }}</label>
                </div>
            </div>

            <div class="app_form_group mb_0">
                {{ form_widget(form.submit) }}
            </div>
            {{ form_end(form) }}
        </section>

        <aside>
            <h2>{{ 'pages.user.menu' | trans | capitalize }}</h2>

            <p>
                <strong>{{ app.user.fullname }}</strong>
            </p>

            <p>
                <strong>Adhérent n°</strong> {{ app.user.registerId }}</p>

            <p>
                <a href="{{ path('user.profile') }}" class="app_button" title="{{ 'pages.user.title' | trans | capitalize }}">
                    {{ 'pages.user.menu' | trans | capitalize }}
                </a>
            </p>

            <p>
                <a href="{{ path('app_logout') }}" class="app_button" title="{{ 'pages.logout.title' | trans | capitalize }}">
                    {{ 'pages.logout.menu' | trans | capitalize }}
                </a>
            </p>
        </aside>
    </article>
{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'pages.user.title' | trans | capitalize }}{% endblock %}

{% block body_class %}user{% endblock %}

{% block body %}
    <article class="aside">
        <section>
            <h1>{{ 'pages.user.title' | trans | capitalize }}</h1>

            <!-- Flash messages -->
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    {% if loop.first %}
                        <div class="app_alert {{ label }}">
                            {{ message | trans | capitalize }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}

            {{ form_start(form, { attr: { 'class': 'app_form'}}) }}
            <div class="app_grid two">
                <div class="app_form_group app_grid_item">
                    {{ form_widget(form.email) }}
                    <label for="{{ form.email.vars.id }}">{{ form.email.vars.label | trans | capitalize }}</label>
                </div>

                <div class="app_form_group app_grid_item">
                    {{ form_widget(form.pseudo) }}
                    <label for="{{ form.pseudo.vars.id }}">{{ form.pseudo.vars.label | trans | capitalize }}</label>
                </div>
            </div>

            <div class="app_grid three">
                <div class="app_form_group app_grid_item">
                    {{ form_widget(form.gender) }}
                    <label for="{{ form.gender.vars.id }}">{{ form.gender.vars.label | trans | capitalize }}</label>
                </div>

                <div class="app_form_group app_grid_item">
                    {{ form_widget(form.firstname) }}
                    <label for="{{ form.firstname.vars.id }}">{{ form.firstname.vars.label | trans | capitalize }}</label>
                </div>

                <div class="app_form_group app_grid_item">
                    {{ form_widget(form.lastname) }}
                    <label for="{{ form.lastname.vars.id }}">{{ form.lastname.vars.label | trans | capitalize }}</label>
                </div>
            </div>

            <div class="app_form_group mb_0">
                {{ form_widget(form.submit) }}
            </div>
            {{ form_end(form) }}
        </section>

        <aside>
            <h2>{{ 'pages.user.menu' | trans | capitalize }}</h2>

            <p>
                <strong>{{ app.user.fullname }}</strong>
            </p>

            <p>
                <strong>Adhérent n°</strong> {{ app.user.registerId }}</p>

            <p>
                <a href="{{ path('user.password') }}" class="app_button" title="{{ 'pages.user.password.title' | trans | capitalize }}">
                    {{ 'pages.user.password.menu' | trans | capitalize }}
                </a>
            </p>

            <p>
                <a href="{{ path('app_logout') }}" class="app_button" title="{{ 'pages.logout.title' | trans | capitalize }}">
                    {{ 'pages.logout.menu' | trans | capitalize }}
                </a>
            </p>
        </aside>
    </article>
{% endblock %}